ALTER TABLE CUSTOMER
    ADD CUST_DOB DATE,
        CUST_AGE INT;

UPDATE CUSTOMER
SET    CUST_DOB = CASE 
                  WHEN CUST_NUM = 1000 THEN '1979-03-15'
                  WHEN CUST_NUM = 1001 THEN '1988-12-22'
				  ELSE CUST_DOB
				  END
UPDATE CUSTOMER
SET    CUST_AGE = CASE
                  WHEN CUST_NUM = 1000 THEN (SELECT DATEDIFF(YY, CUST_DOB, GETDATE()) FROM CUSTOMER WHERE CUST_NUM = 1000)
				  WHEN CUST_NUM = 1001 THEN (SELECT DATEDIFF(YY, CUST_DOB, GETDATE()) FROM CUSTOMER WHERE CUST_NUM = 1001)
				  ELSE CUST_AGE
				  END;
