SELECT B.BOOK_NUM, B.BOOK_TITLE, B.BOOK_SUBJECT, A.AU_LNAME, NUM_BOOKS
FROM BOOK B JOIN WRITES W ON B.BOOK_NUM = W.BOOK_NUM
     JOIN AUTHOR A ON A.AU_ID = W.AU_ID JOIN
	 (SELECT A2.AU_ID, COUNT(B2.BOOK_NUM) AS NUM_BOOKS
	  FROM BOOK B2 JOIN WRITES W2 ON B2.BOOK_NUM = W2.BOOK_NUM
	       JOIN AUTHOR A2 ON W2.AU_ID = A2.AU_ID
	  GROUP BY A2.AU_ID) TABLE1
	  ON A.AU_ID = TABLE1.AU_ID
WHERE B.BOOK_SUBJECT = 'Cloud'
ORDER BY B.BOOK_TITLE, A.AU_LNAME;