SELECT B.BOOK_NUM, B.BOOK_TITLE, B.BOOK_SUBJECT, AVGCOST, (AVGCOST - B.BOOK_COST) AS COST_DIFFERENCE
FROM BOOK B JOIN (SELECT B2.BOOK_SUBJECT, ROUND(AVG(B2.BOOK_COST), 2) AS AVGCOST
                  FROM BOOK B2
				  GROUP BY B2.BOOK_SUBJECT) TABLE1
		    ON B.BOOK_SUBJECT = TABLE1.BOOK_SUBJECT
ORDER BY B.BOOK_NUM, B.BOOK_TITLE;